name: Hexo Auto-Deploy
on: [push]
jobs:
  build:
    name: Hexo Auto-Deploy by GitHub Actions
    runs-on: ubuntu-latest

    steps:
    - name: 1. git checkout...
      uses: actions/checkout@v1
      
    - name: 2. setup nodejs...
      uses: actions/setup-node@v1
    
    - name: 3. install hexo...
      run: |
        npm install hexo-cli -g
        npm install
        
    - name: 4. hexo generate public files...
      run: |
        hexo clean
        hexo g  

    - name: Build and Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./public
        PUBLISH_REPOSITORY: yueziyao/yueziyao.github.io # The repository the action should deploy to.
        BRANCH: master  # The branch the action should deploy to.

