name: Hexo Auto-Deploy
on: [push]
jobs:
  build:
    name: Hexo Auto-Deploy by GitHub Actions
    runs-on: ubuntu-latest

    steps:
    - name: 1. git checkout...
      uses: actions/checkout@v1
      
    - name: 2. setup nodejs...
      uses: actions/setup-node@v1
    
    - name: 3. install hexo...
      run: |
        npm install hexo-cli -g
        npm install
        
    - name: 4. hexo generate public files...
      run: |
        hexo clean
        hexo g  

    - name: Build and Deploy

      uses: JamesIves/github-pages-deploy-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_REPOSITORY: yueziyao/yueziyao.github.io # The repository the action should deploy to.
        BRANCH: master  # The branch the action should deploy to.
        PUBLISH_DIR: ./public # The folder the action should deploy.

